#image: baristaventures/android-fastlane

stages:
  - test

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - sh scripts/cp-env-to-properties.sh

test:
  type: test
  script:
    - gradle
  tags:
    - android